[package]
name = "erigui-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
log = { workspace = true }
glam = { workspace = true }
bitflags = { workspace = true }
slotmap = { workspace = true }
smallvec = { workspace = true }